### ISSUE TITLE
DeFi seems under-filled?

### ISSUE THREAD

**Issue by momack2** [ipfs/ecosystem-directory#168]
![image](https://user-images.githubusercontent.com/618519/123742733-0effbb00-d861-11eb-83f1-15662eb28305.png)

As you can see from the "finance" section here - there are a ton of DeFi projects who use IPFS to ensure they have a decentralized front end - including Uniswap, MyEtherWallet, Kyber Network, and more.

Ravencoin is also a huge user / promoter of IPFS.

Can we get these added to the DeFi category?

**Comment by jessicaschilling** [comment]
@momack2 Of course. 

For background: We'd begun with the original raster diagram and then reached out to these projects personally one by one in order to confirm their details (in particular, the implementations and other tooling they used). At present, projects that responded to one of a series of reach-outs are included in the diagram.

We will include the remaining DeFi projects ASAP based on our own research and reference the PR in this issue. Please accept my apologies.

**Comment by jessicaschilling** [comment]
https://github.com/ipfs/ecosystem-directory/pull/169 adds Uniswap, Ravencoin, Coinomi, MyEtherWallet, Kyber, SwapOnline, Dether.

**Comment by orvn** [comment]
(Note: these new projects are now visible in production)
