### ISSUE TITLE
Pre-final-launch fit and finish

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ecosystem-directory#186]
This issue is for collecting visual or minor functional items that need to be resolved before final launch. Please edit this comment to add any new items. Please open separate issues for larger items.

### Site-wide
- [x] Breadcrumbs should appear at the same distance from top of the page across all pages of the site at all viewport widths; please use the blog placement (at the top of the pile) as a source of truth:
![image](https://user-images.githubusercontent.com/1507828/125471346-350df90e-02fb-40a5-bb93-04ff929c6528.png)
- [ ] #200

### Front page
- [x] This seems like a new issue, but the segment chart is blowing out on narrow mobile (this is 320px wide):
![image](https://user-images.githubusercontent.com/1507828/125532277-9d245cf6-d23d-4821-96a4-4d1731d6ef8e.png)
- [x] Also as referenced in the above screenshot - what would you think about putting a subtle border or shadow around the Filters button so it doesn't feel like an overlay mistake? I think what's nudging me is areas when it appears white-on-white, so just looks like floating text. I'm sure @D3AS8A has thoughts 😊 
- [x] At mobile widths in particular, the margins around the showcase slider make it difficult to tell what the slider actually impacts. Can we please tighten those up? 
![image](https://user-images.githubusercontent.com/1507828/125532507-65f14a7c-e7c4-4685-a0ce-2b117de7d07f.png)
- [x] Am also seeing some strange behavior on resize for the "All projects" header area in general - resulting in margins being huge or occasionally the content sometime disappearing ... I think this has to do with the viewport height just based on behavior, but not sure: 
![image](https://user-images.githubusercontent.com/1507828/125532637-f825a299-c304-4c04-b817-5a99365db2dc.png)
- [x] For null filter results, I know we have the "Clear (x) Selected" item, but would it be possible as well to add a text link in the results area, e.g. "No results found that match the selected filters. Clear all"?
![image](https://user-images.githubusercontent.com/1507828/125533045-d0118f9a-e281-4ea2-988d-14a5a6bf3fd3.png)
- [x] Can the logic for keeping the Filters button out of the footer also extend to content below the footer when the page itself is short on content? Example below. Ignore if this sends you down a massive rabbit hole, please!
![image](https://user-images.githubusercontent.com/1507828/125533196-173a2b72-4a33-4905-b8ff-bab0575e56c6.png)
- [x] At super-wide widths, the white space on the left of the filter panel looks odd. @D3AS8A probably has a better idea than me for a fix, but it could just be a matter of making the filter panel background _start_ at the main page body's left margin: animation-wise, the effect would be of the filter panel sliding out rather than expanding out.
![image](https://user-images.githubusercontent.com/1507828/125534624-3ec47e0a-88ba-469f-9bee-82e4a24253cf.png)
- [x]  If someone clicks on "All projects" in the breadcrumb, they're taken to the "All projects" page with the filter panel open. That's awesome at desktop widths, but at widths narrow enough for the filter panel to take over the whole screen, it's a little jarring. Would it make sense to only expand the filter panel on load for viewports over a certain width?
![image](https://user-images.githubusercontent.com/1507828/125535373-72bd73a6-8d82-44af-aba7-5732d17e2b5e.png)

### Project pages

- [x] Can the collapse arrows please be vertically centered on the headers they correspond to?
![image](https://user-images.githubusercontent.com/1507828/125533449-08c35997-bf6f-43ec-83ce-0c3b5f94494a.png)
- [x] Vertical margins overall on the "Featured projects" section are a little large, particularly at mobile widths: 
![image](https://user-images.githubusercontent.com/1507828/125533577-503edcf3-267a-4e29-b2d7-536208bff1ca.png)
![image](https://user-images.githubusercontent.com/1507828/125533587-527b5b32-bd61-44bf-a274-c4af194f9daa.png)
- [x] Additionally, for super-wide widths, can you please make the "Featured projects" section no wider than the main body content width? 
![image](https://user-images.githubusercontent.com/1507828/125534341-bb45e05a-5cd3-40a8-9715-017085fb6fc8.png)

- [x] Big-number boxes and CTAs are a little awkward at mobile widths. Can we please have big-number labels (e.g. "Content identifiers") pack from the top rather than the bottom, and increase the font size of the CTA title (e.g. "Audius case study") - or probably just _not decrease_ it from its previous size?
![image](https://user-images.githubusercontent.com/1507828/125533908-44eb6555-63ec-4bf4-9b9e-0358ed2ad73a.png)
![image](https://user-images.githubusercontent.com/1507828/125533927-2a3d418e-6cdf-44f1-a185-d4ffa2a0ecff.png)
- [x] For viewport widths where the big numbers/CTAs stack, can the project description please span the full width of the viewport?
![image](https://user-images.githubusercontent.com/1507828/125534197-759cb250-75eb-4de8-ab15-a15f52bde90e.png)

- [x] Don't want to override @D3AS8A if she has strong feels on this one, but I've seen folks miss the primary CTA button for "Project website" in cases where there's also a button in the cards (big number/CTA) section. I think the outline style is tripping them up and wonder if it'd be better to use the same primary button style as on the blog/IPFS website (i.e. the style in the "Subscribe" button in the footer)? 
![image](https://user-images.githubusercontent.com/1507828/125535015-a3017070-9da2-4ef3-be0b-534458ed4b58.png)
- [x] For truncated content in the "Key info" section, the question mark hover is a little weird - honestly I think this was an artifact in an earlier wireframe that escaped deletion. Could we please just remove the question mark icon entirely and invoke the hover text by hovering on the truncated text, like on the front page? 
![image](https://user-images.githubusercontent.com/1507828/125535648-e0b074b9-63cf-4441-85e6-1ebb10f6a24e.png)

**Comment by timelytree** [comment]
> At mobile widths in particular, the margins around the showcase slider make it difficult to tell what the slider actually impacts. Can we please tighten those up?

@jessicaschilling this is a bit of a tough one. I managed to tighten it up by 2 rems but the main issue stems from the fact that the slider contains cards with unequal amounts of card title/description text. Because the slider takes the height of the largest card, in some cases when there's less text, it ends up looking like there's just randomly more space *tear (screenshots below)

This is fixable by giving the slider an adaptive height but also would possibly be worse UX because then the slider control would move up/down as the slider re-adjusts height, often moving from under one's finger on mobile. I would make the suggestion to instead select projects to feature that all have equal (or almost equal) amounts of text → or to add more text to the currently featured projects. So ultimately fix by tweaking copy rather than functionality.

What do you think @jessicaschilling? 🙂 

**one-liners**
<img width="315" alt="Screen Shot 2021-07-15 at 11 01 30" src="https://user-images.githubusercontent.com/11708190/125835837-0216dc89-1924-4fd0-bf68-52c4d0955cd7.png">

**two-liners**
<img width="312" alt="Screen Shot 2021-07-15 at 11 03 34" src="https://user-images.githubusercontent.com/11708190/125835909-7cae6431-2928-427b-999f-38477d40e18d.png">

**Comment by jessicaschilling** [comment]
@timelytree oh, right - that totally makes sense. Can definitely tweak content, I think your approach makes the most sense. And in any case, the 2rem helps a lot 😊

**Comment by timelytree** [comment]
@jessicaschilling for this item:

> At super-wide widths, the white space on the left of the filter panel looks odd. @D3AS8A probably has a better idea than me for a fix, but it could just be a matter of making the filter panel background start at the main page body's left margin: animation-wise, the effect would be of the filter panel sliding out rather than expanding out.

Can you elaborate on this part:

> filter panel _**sliding out**_ rather than _**expanding out**_

Also looks-wise we had the idea of making the white fade rather than go forever, what do you think? 🙂 

<img width="1258" alt="Screen Shot 2021-07-23 at 09 44 17" src="https://user-images.githubusercontent.com/11708190/126814771-e8b06d01-af78-40f3-bbf9-c50dce1b840d.png">

**Comment by jessicaschilling** [comment]
The fade works! And negates my "sliding out" comment, so feel free to ignore that.

**Comment by D3AS8A** [comment]
>     * Don't want to override @D3AS8A if she has strong feels on this one, but I've seen folks miss the primary CTA button for "Project website" in cases where there's also a button in the cards (big number/CTA) section. I think the outline style is tripping them up and wonder if it'd be better to use the same primary button style as on the blog/IPFS website (i.e. the style in the "Subscribe" button in the footer)?

@jessicaschilling 

Thanks for flagging this. See image below of proposed solution to reorient users attention to primary CTA (on left). Initially I placed the case study as primary and project site as secondary. 

<img width="1335" alt="Screen Shot 2021-07-23 at 2 29 44 PM" src="https://user-images.githubusercontent.com/72217652/126826467-10cb86b1-61ba-4fed-9808-bec67e59730c.png">

Notes for @timelytree 
- box border to #F1F3F2
- in box cta button inverse, filled on hover (button height increased to 40px)
- see other values in XD file

**Comment by jessicaschilling** [comment]
@D3AS8A Looks good, thanks!

**Comment by timelytree** [comment]
@jessicaschilling I hope you don't mind → I moved the 2nd item in the list (regarding accessibility) into its own Issue (#200) as it's sort of its own thing that we're going to tackle (starting with tabbing through the nav). We'll populate the Issue with more details soon! 🙂

**Comment by timelytree** [comment]
Hey @jessicaschilling 👋🏼 I just wanted to outline the list of items that we have left on the docket. I don't think any of these are showstoppers for a hard launch but I'll let you tell me otherwise 😅

- **SEO** → already complete and live, just adding some extras and doing an audit, scheduled for **this week**
- **Accessibility** → mostly complete and live, currently underway, scheduled for **this week**
- **Clean up and abstract `nuxt-module-ipfs`** → currently underway, scheduled for **next week**
- **Abstract out Shipyard** → currently underway, scheduled for **next week**
- **Embeddable view** → already complete but not live, just making final very minor design tweaks, scheduled for **this week**

**Comment by jessicaschilling** [comment]
Awesome, thanks @timelytree! I think we're in a good place to start promoting this more widely. I've asked the marketing team to get it added to their list of "evergreen" social promo items, and will get a blog post in the works announcing the directory.

**Comment by jessicaschilling** [comment]
For anyone who's following along at home: work in the depersonalized boilerplate repo is happening at https://github.com/ipfs-shipyard/ecosystem-directory 😊
